### ISSUE TITLE
Unable to change game directory

### ISSUE THREAD

**Issue by skydox295** [theamazingfedex/mhmm#9]
When clicking the "x" next to your directory, you're brought to a white page and unable to clear the directory

**Comment by skydox295** [comment]
Clearing cookies cleared the selected directory and allowed me to change

**Comment by theamazingfedex** [comment]
Thanks for the report. The latest release should resolve this issue.

**Comment by theamazingfedex** [comment]
Closing this as the issue should have been resolved by #10
